name: ci

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - run: corepack enable

      - uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint project
        run: pnpm lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - run: corepack enable

      - uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test types
        run: pnpm test:types

      - name: Build project
        run: pnpm build

      - name: Test project
        run: pnpm test -- --coverage

      - name: Coverage
        uses: codecov/codecov-action@v5
